# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24fa49693522523d7f89116d38620285a89c1c5a38fe8300231ce29356621a486cea8653b74baad737ef792d73e1318199325666ae0fafc5f06d3a803dd6e346

test:
  secret_key_base: 07296d23b2bc0cc6137d3fc81b3a6307970a50c0e6b7b6f2f332cf7f11441e25d7cafa255676cefa4b1d75aa80f7e6eb963e26a19cf39d91ccd63e7f5dc40f19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
